### ISSUE TITLE
can't click "ok" in iphone SE 2020

### ISSUE THREAD

**Issue by directhub** [riversx/riversx.github.io#1]
![IMG_3650](https://github.com/user-attachments/assets/f2cd6c53-ab3d-43cb-93a0-49caf6f0b5e7)
I love this app, but on Iphone SE 2020, after I complete a test, the "ok" button doesn't work, nothing happens if you tap it. So I have to shut down the app and relaunch.

Thanks in advance if you take the time to fix it!

**Comment by riversx** [comment]
thanks @directhub 
I will check in the next weeks

**Comment by riversx** [comment]
@directhub  
I think this problem can be related with the Accessibility settings: Display & Text Size.
Can you please send me the size of text you are using in your phone ?
Thanks in advance

**Comment by directhub** [comment]
Hi, I'm sure I have standard Display & Text Size as I never touched it.
I am attaching the screens you requested anyway. I confirm everything is "factory" settings.
Thanks for your time!
![IMG_E3586CE6EA0C-1](https://github.com/user-attachments/assets/1fe3ce36-dc1a-4db6-a5d3-24379ecaef29)
![IMG_CE0F1BFF0890-1](https://github.com/user-attachments/assets/23ffac36-973b-4703-96cb-53ffd3e91cb9)

**Comment by riversx** [comment]
OK Thanks 
I will do some checks

**Comment by riversx** [comment]
@directhub 
I tested the app on iPphoe SE simulator and I got this resolution 

![Image](https://github.com/user-attachments/assets/94b9f177-c314-442e-9105-b92d73f49156)

I will try to resize the results page

**Comment by riversx** [comment]
@directhub 
can you check this page: 
"Schermo e dimensioni testo" => "Testo più grande" 
![Image](https://github.com/user-attachments/assets/09c284ec-6217-464d-8f3e-c9938927786a)

**Comment by directhub** [comment]
Hi,

I confirm that the simulator is inaccurate:
![IMG_0256](https://github.com/user-attachments/assets/73a38337-966a-4d7b-ac15-9fac66f88109)
And here is my settings:
![IMG_9AA4E28B116F-1](https://github.com/user-attachments/assets/1f8053c8-efeb-46b5-a2ec-2967c9561079)

**Comment by riversx** [comment]
A new version 1.5.1 for iOS has been released today
Can you check if this solve your problem 
Let me know !

**Comment by directhub** [comment]
Upgraded to 1.5.1, but still the ok button is not clickable:

![IMG_7EF5D43542C8-1](https://github.com/user-attachments/assets/0f614a8c-57e3-4b1d-867a-fc672fd3161e)

**Comment by riversx** [comment]
hi @directhub 
in the new version 1.6.0 the OK button has been replaced with a close icon on the top 
can you check if this layout works for your device ?
thanks in advance 
Boris

**Comment by directhub** [comment]
yes it works now
Thanks for your help!
